/**
 * Verkle Flat — Cross-Validation Against go-verkle Reference Vectors
 *
 * Reads verkle_vectors.bin (generated by gen_verkle_vectors/main.go)
 * and validates that the flat updater produces identical root hashes.
 *
 * Tests both build scenarios (insert all at once) and multiblock
 * scenarios (incremental block-by-block updates).
 *
 * Also tests revert, persistence (sync+reopen), and value readback.
 */

#include "verkle_flat.h"
#include "pedersen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

/* =========================================================================
 * Test Infrastructure
 * ========================================================================= */

static int tests_passed = 0;
static int tests_failed = 0;
static int scenarios_passed = 0;
static int scenarios_failed = 0;

#define ASSERT(cond, ...)                                              \
    do {                                                               \
        if (!(cond)) {                                                 \
            printf("  FAIL (line %d): ", __LINE__);                    \
            printf(__VA_ARGS__);                                       \
            printf("\n");                                              \
            tests_failed++;                                            \
            return false;                                              \
        } else {                                                       \
            tests_passed++;                                            \
        }                                                              \
    } while (0)

#define VAL_DIR  "/tmp/test_vf_cross_val"
#define COMM_DIR "/tmp/test_vf_cross_comm"

static void cleanup(void) {
    system("rm -rf " VAL_DIR " " COMM_DIR);
}

static void print_hex(const uint8_t *data, int len) {
    for (int i = 0; i < len; i++) printf("%02x", data[i]);
}

/* =========================================================================
 * Binary Reader
 * ========================================================================= */

typedef struct {
    const uint8_t *data;
    size_t pos;
    size_t len;
} reader_t;

static uint16_t read_u16(reader_t *r) {
    uint16_t v = (uint16_t)r->data[r->pos] |
                 ((uint16_t)r->data[r->pos + 1] << 8);
    r->pos += 2;
    return v;
}

static uint32_t read_u32(reader_t *r) {
    uint32_t v = (uint32_t)r->data[r->pos] |
                 ((uint32_t)r->data[r->pos + 1] << 8) |
                 ((uint32_t)r->data[r->pos + 2] << 16) |
                 ((uint32_t)r->data[r->pos + 3] << 24);
    r->pos += 4;
    return v;
}

static const uint8_t *read_bytes(reader_t *r, size_t n) {
    const uint8_t *p = r->data + r->pos;
    r->pos += n;
    return p;
}

/* =========================================================================
 * Flat Helpers
 * ========================================================================= */

static verkle_flat_t *create_fresh(void) {
    cleanup();
    return verkle_flat_create(VAL_DIR, COMM_DIR);
}

static void get_root(const verkle_flat_t *vf, uint8_t out[32]) {
    verkle_flat_root_hash(vf, out);
}

/* =========================================================================
 * Build Scenario: insert all keys, commit, check root
 * ========================================================================= */

static bool run_build_scenario(const char *name, reader_t *r) {
    uint32_t num_keys = read_u32(r);

    verkle_flat_t *vf = create_fresh();
    ASSERT(vf != NULL, "create flat for '%s'", name);

    ASSERT(verkle_flat_begin_block(vf, 1), "begin_block for '%s'", name);

    for (uint32_t i = 0; i < num_keys; i++) {
        const uint8_t *key = read_bytes(r, 32);
        const uint8_t *val = read_bytes(r, 32);
        ASSERT(verkle_flat_set(vf, key, val), "set key %u for '%s'", i, name);
    }

    ASSERT(verkle_flat_commit_block(vf), "commit_block for '%s'", name);

    const uint8_t *expected = read_bytes(r, 32);
    uint8_t got[32];
    get_root(vf, got);

    if (memcmp(got, expected, 32) != 0) {
        printf("  FAIL: root mismatch for '%s'\n", name);
        printf("    expected: "); print_hex(expected, 32); printf("\n");
        printf("    got:      "); print_hex(got, 32); printf("\n");
        tests_failed++;
        verkle_flat_destroy(vf);
        return false;
    }
    tests_passed++;

    /* Verify value readback */
    r->pos -= (size_t)num_keys * 64 + 32; /* rewind to keys */
    for (uint32_t i = 0; i < num_keys; i++) {
        const uint8_t *key = read_bytes(r, 32);
        const uint8_t *val = read_bytes(r, 32);
        uint8_t readback[32];
        ASSERT(verkle_flat_get(vf, key, readback),
               "get key %u for '%s'", i, name);
        ASSERT(memcmp(readback, val, 32) == 0,
               "value mismatch key %u for '%s'", i, name);
    }
    r->pos += 32; /* skip expected root (already consumed above) */

    verkle_flat_destroy(vf);
    return true;
}

/* =========================================================================
 * Multiblock Scenario: initial + incremental blocks, check root each step
 * ========================================================================= */

static bool run_multiblock_scenario(const char *name, reader_t *r) {
    /* Read initial keys */
    uint32_t num_initial = read_u32(r);

    verkle_flat_t *vf = create_fresh();
    ASSERT(vf != NULL, "create flat for '%s'", name);

    /* Block 0: initial state */
    ASSERT(verkle_flat_begin_block(vf, 0), "begin_block(0) for '%s'", name);
    for (uint32_t i = 0; i < num_initial; i++) {
        const uint8_t *key = read_bytes(r, 32);
        const uint8_t *val = read_bytes(r, 32);
        ASSERT(verkle_flat_set(vf, key, val),
               "set initial key %u for '%s'", i, name);
    }
    ASSERT(verkle_flat_commit_block(vf), "commit initial for '%s'", name);

    const uint8_t *initial_root = read_bytes(r, 32);
    uint8_t got[32];
    get_root(vf, got);

    if (memcmp(got, initial_root, 32) != 0) {
        printf("  FAIL: initial root mismatch for '%s'\n", name);
        printf("    expected: "); print_hex(initial_root, 32); printf("\n");
        printf("    got:      "); print_hex(got, 32); printf("\n");
        tests_failed++;
        verkle_flat_destroy(vf);
        return false;
    }
    tests_passed++;

    /* Process blocks */
    uint32_t num_blocks = read_u32(r);
    for (uint32_t b = 0; b < num_blocks; b++) {
        ASSERT(verkle_flat_begin_block(vf, b + 1),
               "begin_block(%u) for '%s'", b + 1, name);

        uint32_t num_ops = read_u32(r);
        for (uint32_t i = 0; i < num_ops; i++) {
            const uint8_t *key = read_bytes(r, 32);
            const uint8_t *val = read_bytes(r, 32);
            ASSERT(verkle_flat_set(vf, key, val),
                   "set block %u key %u for '%s'", b + 1, i, name);
        }

        ASSERT(verkle_flat_commit_block(vf),
               "commit block %u for '%s'", b + 1, name);

        const uint8_t *expected = read_bytes(r, 32);
        get_root(vf, got);

        if (memcmp(got, expected, 32) != 0) {
            printf("  FAIL: block %u root mismatch for '%s'\n", b + 1, name);
            printf("    expected: "); print_hex(expected, 32); printf("\n");
            printf("    got:      "); print_hex(got, 32); printf("\n");
            tests_failed++;
            verkle_flat_destroy(vf);
            return false;
        }
        tests_passed++;
    }

    /* Test persistence: sync, destroy, reopen, check root */
    verkle_flat_sync(vf);
    get_root(vf, got); /* save root before destroy */
    uint8_t saved_root[32];
    memcpy(saved_root, got, 32);
    verkle_flat_destroy(vf);

    vf = verkle_flat_open(VAL_DIR, COMM_DIR);
    ASSERT(vf != NULL, "reopen flat for '%s'", name);

    uint8_t reopen_root[32];
    get_root(vf, reopen_root);
    ASSERT(memcmp(reopen_root, saved_root, 32) == 0,
           "root changed after reopen for '%s'", name);

    verkle_flat_destroy(vf);
    return true;
}

/* =========================================================================
 * Revert Test: build 2 blocks, revert second, verify root matches block 1
 * ========================================================================= */

static bool test_revert(void) {
    printf("\n--- Revert Test ---\n");

    verkle_flat_t *vf = create_fresh();
    if (!vf) { printf("  FAIL: create\n"); tests_failed++; return false; }

    /* Block 1: insert some keys */
    uint8_t key1[32] = {0}; key1[0] = 0xAA;
    uint8_t key2[32] = {0}; key2[0] = 0xBB;
    uint8_t val1[32] = {0}; val1[0] = 0x11;
    uint8_t val2[32] = {0}; val2[0] = 0x22;

    ASSERT(verkle_flat_begin_block(vf, 1), "begin block 1");
    ASSERT(verkle_flat_set(vf, key1, val1), "set key1");
    ASSERT(verkle_flat_set(vf, key2, val2), "set key2");
    ASSERT(verkle_flat_commit_block(vf), "commit block 1");

    uint8_t root_after_b1[32];
    get_root(vf, root_after_b1);

    /* Block 2: modify key1 */
    uint8_t val1_new[32] = {0}; val1_new[0] = 0xFF;
    ASSERT(verkle_flat_begin_block(vf, 2), "begin block 2");
    ASSERT(verkle_flat_set(vf, key1, val1_new), "update key1");
    ASSERT(verkle_flat_commit_block(vf), "commit block 2");

    uint8_t root_after_b2[32];
    get_root(vf, root_after_b2);
    ASSERT(memcmp(root_after_b1, root_after_b2, 32) != 0,
           "root should change after block 2");

    /* Revert block 2 */
    ASSERT(verkle_flat_revert_block(vf), "revert block 2");

    uint8_t root_after_revert[32];
    get_root(vf, root_after_revert);
    ASSERT(memcmp(root_after_revert, root_after_b1, 32) == 0,
           "root should match block 1 after revert");

    /* Verify value reverted */
    uint8_t readback[32];
    ASSERT(verkle_flat_get(vf, key1, readback), "get key1 after revert");
    ASSERT(memcmp(readback, val1, 32) == 0,
           "key1 value should be original after revert");

    printf("  PASS: revert restores root and values\n");
    verkle_flat_destroy(vf);
    return true;
}

/* =========================================================================
 * Determinism Test: same ops in different order should give same root
 * ========================================================================= */

static bool test_determinism(void) {
    printf("\n--- Determinism Test ---\n");

    /* Build A: insert keys in order 0,1,2,...,9 */
    cleanup();
    verkle_flat_t *vf_a = verkle_flat_create(VAL_DIR, COMM_DIR);
    if (!vf_a) { printf("  FAIL: create A\n"); tests_failed++; return false; }

    verkle_flat_begin_block(vf_a, 1);
    for (int i = 0; i < 10; i++) {
        uint8_t key[32] = {0};
        key[0] = (uint8_t)(i * 0x11);
        uint8_t val[32] = {0};
        val[0] = (uint8_t)(i + 1);
        verkle_flat_set(vf_a, key, val);
    }
    verkle_flat_commit_block(vf_a);

    uint8_t root_a[32];
    get_root(vf_a, root_a);
    verkle_flat_destroy(vf_a);

    /* Build B: insert keys in reverse order 9,8,...,0 */
    cleanup();
    verkle_flat_t *vf_b = verkle_flat_create(VAL_DIR, COMM_DIR);
    if (!vf_b) { printf("  FAIL: create B\n"); tests_failed++; return false; }

    verkle_flat_begin_block(vf_b, 1);
    for (int i = 9; i >= 0; i--) {
        uint8_t key[32] = {0};
        key[0] = (uint8_t)(i * 0x11);
        uint8_t val[32] = {0};
        val[0] = (uint8_t)(i + 1);
        verkle_flat_set(vf_b, key, val);
    }
    verkle_flat_commit_block(vf_b);

    uint8_t root_b[32];
    get_root(vf_b, root_b);
    verkle_flat_destroy(vf_b);

    ASSERT(memcmp(root_a, root_b, 32) == 0,
           "insertion order should not affect root");

    printf("  PASS: root is deterministic regardless of insertion order\n");
    return true;
}

/* =========================================================================
 * Main
 * ========================================================================= */

int main(int argc, char *argv[]) {
    pedersen_init();

    /* Find vectors file */
    const char *vec_path = "verkle/tests/verkle_vectors.bin";
    if (argc > 1)
        vec_path = argv[1];

    FILE *f = fopen(vec_path, "rb");
    if (!f) {
        /* Try relative to executable */
        f = fopen("verkle_vectors.bin", "rb");
    }
    if (!f) {
        fprintf(stderr, "Cannot open %s\n", vec_path);
        fprintf(stderr, "Generate with: cd verkle/tests/gen_verkle_vectors && go run main.go\n");
        return 1;
    }

    fseek(f, 0, SEEK_END);
    size_t fsize = (size_t)ftell(f);
    fseek(f, 0, SEEK_SET);

    uint8_t *data = malloc(fsize);
    if (fread(data, 1, fsize, f) != fsize) {
        fprintf(stderr, "Read error\n");
        fclose(f);
        return 1;
    }
    fclose(f);

    reader_t r = { .data = data, .pos = 0, .len = fsize };
    uint32_t num_scenarios = read_u32(&r);
    printf("Loaded %u scenarios from %s (%zu bytes)\n\n", num_scenarios, vec_path, fsize);

    /* Run reference vector scenarios */
    for (uint32_t s = 0; s < num_scenarios; s++) {
        uint16_t name_len = read_u16(&r);
        char name[256];
        memcpy(name, read_bytes(&r, name_len), name_len);
        name[name_len] = '\0';

        uint8_t scenario_type = *read_bytes(&r, 1);

        printf("[%u/%u] %s (%s)...",
               s + 1, num_scenarios, name,
               scenario_type == 0 ? "build" : "multiblock");

        bool ok;
        if (scenario_type == 0) {
            ok = run_build_scenario(name, &r);
        } else {
            ok = run_multiblock_scenario(name, &r);
        }

        if (ok) {
            printf(" PASS\n");
            scenarios_passed++;
        } else {
            scenarios_failed++;
        }
    }

    /* Additional standalone tests */
    test_revert();
    test_determinism();

    /* Summary */
    printf("\n========================================\n");
    printf("Scenarios: %d passed, %d failed (of %u)\n",
           scenarios_passed, scenarios_failed, num_scenarios);
    printf("Assertions: %d passed, %d failed\n", tests_passed, tests_failed);
    printf("========================================\n");

    free(data);
    cleanup();

    return tests_failed > 0 ? 1 : 0;
}
