/*
 * MPT Store Cross-Validation against Python reference vectors.
 *
 * Reads binary test vectors from database/tests/mpt_vectors.bin
 * (generated by gen_mpt_vectors.py using Python's HexaryTrie).
 *
 * For "build" scenarios: insert all keys via mpt_store, verify root.
 * For "update" scenarios: insert initial keys, verify root, then apply
 * dirty updates, verify new root.
 */

#include "mpt_store.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

/* =========================================================================
 * Helpers
 * ========================================================================= */

static const char *STORE_PATH = "/tmp/test_mpt_store_vectors";

static void cleanup(void) {
    unlink("/tmp/test_mpt_store_vectors.idx");
    unlink("/tmp/test_mpt_store_vectors.dat");
}

static void print_hash(const uint8_t h[32]) {
    for (int i = 0; i < 32; i++) printf("%02x", h[i]);
}

/* Read exactly n bytes from file. Returns false on short read. */
static bool read_exact(FILE *f, void *buf, size_t n) {
    return fread(buf, 1, n, f) == n;
}

static uint32_t read_u32(FILE *f) {
    uint32_t v;
    read_exact(f, &v, 4);
    return v; /* already LE on x86 */
}

static uint16_t read_u16(FILE *f) {
    uint16_t v;
    read_exact(f, &v, 2);
    return v;
}

typedef struct {
    uint8_t key[32];
    uint8_t *value;
    uint16_t value_len;
} kv_entry_t;

static kv_entry_t *read_kv_entries(FILE *f, uint32_t *out_count) {
    uint32_t n = read_u32(f);
    *out_count = n;
    if (n == 0) return NULL;

    kv_entry_t *entries = calloc(n, sizeof(*entries));
    for (uint32_t i = 0; i < n; i++) {
        read_exact(f, entries[i].key, 32);
        entries[i].value_len = read_u16(f);
        if (entries[i].value_len > 0) {
            entries[i].value = malloc(entries[i].value_len);
            read_exact(f, entries[i].value, entries[i].value_len);
        }
    }
    return entries;
}

static void free_entries(kv_entry_t *entries, uint32_t count) {
    if (!entries) return;
    for (uint32_t i = 0; i < count; i++)
        free(entries[i].value);
    free(entries);
}

/* =========================================================================
 * Main
 * ========================================================================= */

int main(int argc, char **argv) {
    const char *vectors_path = "database/tests/mpt_vectors.bin";
    if (argc > 1) vectors_path = argv[1];

    FILE *f = fopen(vectors_path, "rb");
    if (!f) {
        fprintf(stderr, "Cannot open %s\n", vectors_path);
        fprintf(stderr, "Usage: %s [path/to/mpt_vectors.bin]\n", argv[0]);
        return 1;
    }

    uint32_t num_scenarios = read_u32(f);
    printf("MPT Store Cross-Validation: %u scenarios\n", num_scenarios);
    printf("==========================================\n");

    int passed = 0, failed = 0, assertions = 0;

    for (uint32_t s = 0; s < num_scenarios; s++) {
        uint8_t scenario_type;
        read_exact(f, &scenario_type, 1);

        /* Read initial key-value pairs */
        uint32_t initial_count;
        kv_entry_t *initial = read_kv_entries(f, &initial_count);

        /* Read expected root after build */
        uint8_t expected_root[32];
        read_exact(f, expected_root, 32);

        /* Build the trie */
        cleanup();
        mpt_store_t *ms = mpt_store_create(STORE_PATH, initial_count + 1024);
        if (!ms) {
            fprintf(stderr, "  Scenario %u: FAILED to create store\n", s + 1);
            failed++;
            free_entries(initial, initial_count);
            continue;
        }

        if (initial_count > 0) {
            mpt_store_begin_batch(ms);
            for (uint32_t i = 0; i < initial_count; i++) {
                mpt_store_update(ms, initial[i].key,
                                 initial[i].value, initial[i].value_len);
            }
            mpt_store_commit_batch(ms);
        }

        /* Verify build root */
        uint8_t got_root[32];
        mpt_store_root(ms, got_root);
        assertions++;

        bool build_ok = (memcmp(got_root, expected_root, 32) == 0);

        if (scenario_type == 0) {
            /* Build-only scenario */
            printf("  %2u. build  (%4u keys)      ", s + 1, initial_count);
            if (build_ok) {
                printf("PASS\n");
                passed++;
            } else {
                printf("FAIL\n");
                printf("      got:  "); print_hash(got_root); printf("\n");
                printf("      exp:  "); print_hash(expected_root); printf("\n");
                failed++;
            }
        } else {
            /* Update scenario: read dirty entries */
            uint32_t dirty_count;
            kv_entry_t *dirty = read_kv_entries(f, &dirty_count);

            uint8_t expected_updated_root[32];
            read_exact(f, expected_updated_root, 32);

            printf("  %2u. update (%4u + %3u dirty) ", s + 1,
                   initial_count, dirty_count);

            if (!build_ok) {
                printf("FAIL (build phase)\n");
                printf("      got:  "); print_hash(got_root); printf("\n");
                printf("      exp:  "); print_hash(expected_root); printf("\n");
                failed++;
                free_entries(dirty, dirty_count);
                free_entries(initial, initial_count);
                mpt_store_destroy(ms);
                continue;
            }

            /* Apply dirty updates */
            mpt_store_begin_batch(ms);
            for (uint32_t i = 0; i < dirty_count; i++) {
                if (dirty[i].value_len == 0) {
                    mpt_store_delete(ms, dirty[i].key);
                } else {
                    mpt_store_update(ms, dirty[i].key,
                                     dirty[i].value, dirty[i].value_len);
                }
            }
            mpt_store_commit_batch(ms);

            mpt_store_root(ms, got_root);
            assertions++;

            if (memcmp(got_root, expected_updated_root, 32) == 0) {
                printf("PASS\n");
                passed++;
            } else {
                printf("FAIL (update phase)\n");
                printf("      got:  "); print_hash(got_root); printf("\n");
                printf("      exp:  "); print_hash(expected_updated_root); printf("\n");
                failed++;
            }

            free_entries(dirty, dirty_count);
        }

        mpt_store_destroy(ms);
        free_entries(initial, initial_count);
    }

    fclose(f);
    cleanup();

    printf("\n%d/%d scenarios passed (%d assertions)\n",
           passed, passed + failed, assertions);
    return failed > 0 ? 1 : 0;
}
