/**
 * MPT Test Vector Verification
 * 
 * This test reads JSON test vectors generated by generate_state_tests.py
 * and validates the MPT implementation against expected state roots.
 * 
 * Usage: test_mpt_vectors [path_to_json]
 * Default: ../tools/mpt_test_vectors.json
 */

#include "mpt.h"
#include "rlp.h"
#include "keccak256.h"
#include "uint256.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>
#include <cjson/cJSON.h>

/**
 * Ethereum account structure
 */
typedef struct {
    uint8_t address[20];
    uint64_t nonce;
    uint256_t balance;
    uint8_t storage_root[32];
    uint8_t code_hash[32];
} eth_account_t;

/**
 * Convert hex string to bytes
 */
static size_t hex_to_bytes(const char *hex_str, uint8_t *bytes, size_t max_len) {
    if (hex_str[0] == '0' && hex_str[1] == 'x') {
        hex_str += 2;
    }
    
    size_t hex_len = strlen(hex_str);
    size_t byte_len = hex_len / 2;
    
    if (byte_len > max_len) {
        return 0;
    }
    
    for (size_t i = 0; i < byte_len; i++) {
        char byte_str[3] = {hex_str[i*2], hex_str[i*2 + 1], '\0'};
        bytes[i] = (uint8_t)strtol(byte_str, NULL, 16);
    }
    
    return byte_len;
}

/**
 * Parse uint256 from decimal string
 */
static uint256_t parse_uint256_decimal(const char *str) {
    uint256_t result = uint256_from_uint64(0);
    
    for (const char *p = str; *p; p++) {
        if (*p >= '0' && *p <= '9') {
            uint256_t ten = uint256_from_uint64(10);
            uint256_t digit = uint256_from_uint64(*p - '0');
            result = uint256_mul(&result, &ten);
            result = uint256_add(&result, &digit);
        }
    }
    
    return result;
}

/**
 * Encode Ethereum account as RLP
 * Format: RLP([nonce, balance, storage_root, code_hash])
 */
static bytes_t encode_account(const eth_account_t *account) {
    rlp_item_t *list = rlp_list_new();
    
    // 1. Nonce
    rlp_list_append(list, rlp_uint64(account->nonce));
    
    // 2. Balance (uint256_t as big-endian bytes)
    uint8_t balance_bytes[32];
    uint256_to_bytes(&account->balance, balance_bytes);
    
    // Remove leading zeros for RLP encoding
    int start = 0;
    while (start < 32 && balance_bytes[start] == 0) start++;
    
    if (start == 32) {
        rlp_list_append(list, rlp_string(NULL, 0));
    } else {
        rlp_list_append(list, rlp_string(balance_bytes + start, 32 - start));
    }
    
    // 3. Storage root (32 bytes)
    rlp_list_append(list, rlp_string(account->storage_root, 32));
    
    // 4. Code hash (32 bytes)
    rlp_list_append(list, rlp_string(account->code_hash, 32));
    
    bytes_t encoded = rlp_encode(list);
    rlp_item_free(list);
    
    return encoded;
}

/**
 * Hash address to get MPT key (Keccak256 of address)
 */
static void hash_address(const uint8_t *address, uint8_t *hash_out) {
    SHA3_CTX ctx;
    keccak_init(&ctx);
    keccak_update(&ctx, address, 20);
    keccak_final(&ctx, hash_out);
}

/**
 * Parse account from JSON object
 */
static bool parse_account(cJSON *json_account, eth_account_t *account) {
    // Address
    cJSON *address = cJSON_GetObjectItem(json_account, "address");
    if (!address || !cJSON_IsString(address)) return false;
    if (hex_to_bytes(address->valuestring, account->address, 20) != 20) return false;
    
    // Nonce
    cJSON *nonce = cJSON_GetObjectItem(json_account, "nonce");
    if (!nonce || !cJSON_IsNumber(nonce)) return false;
    account->nonce = (uint64_t)nonce->valuedouble;
    
    // Balance - can be number or string for large values
    cJSON *balance = cJSON_GetObjectItem(json_account, "balance");
    if (!balance) return false;
    
    if (cJSON_IsNumber(balance)) {
        account->balance = uint256_from_uint64((uint64_t)balance->valuedouble);
    } else if (cJSON_IsString(balance)) {
        account->balance = parse_uint256_decimal(balance->valuestring);
    } else {
        return false;
    }
    
    // Storage root
    cJSON *storage_root = cJSON_GetObjectItem(json_account, "storage_root");
    if (!storage_root || !cJSON_IsString(storage_root)) return false;
    if (hex_to_bytes(storage_root->valuestring, account->storage_root, 32) != 32) return false;
    
    // Code hash
    cJSON *code_hash = cJSON_GetObjectItem(json_account, "code_hash");
    if (!code_hash || !cJSON_IsString(code_hash)) return false;
    if (hex_to_bytes(code_hash->valuestring, account->code_hash, 32) != 32) return false;
    
    return true;
}

/**
 * Test a single test case
 */
static bool test_case(const char *test_name, cJSON *accounts_array, const char *expected_root_hex) {
    // Parse expected root
    mpt_hash_t expected_root;
    if (hex_to_bytes(expected_root_hex, expected_root.bytes, MPT_HASH_SIZE) != MPT_HASH_SIZE) {
        printf("FAILED: %s - Invalid expected root hash\n", test_name);
        return false;
    }
    
    // Initialize MPT
    mpt_state_t state = {0};
    if (!mpt_init(&state)) {
        printf("FAILED: %s - Could not initialize MPT\n", test_name);
        return false;
    }
    
    // Parse and insert each account
    int num_accounts = cJSON_GetArraySize(accounts_array);
    
    for (int i = 0; i < num_accounts; i++) {
        cJSON *json_account = cJSON_GetArrayItem(accounts_array, i);
        if (!json_account) continue;
        
        eth_account_t account;
        if (!parse_account(json_account, &account)) {
            printf("FAILED: %s - Could not parse account %d\n", test_name, i);
            mpt_destroy(&state);
            return false;
        }
        
        // Encode account
        bytes_t encoded = encode_account(&account);
        
        // Use raw address as key (20 bytes), NOT the hash!
        // Ethereum state trie uses raw addresses as keys
        
        // Insert into MPT
        if (!mpt_insert(&state, account.address, 20, encoded.data, encoded.len)) {
            printf("FAILED: %s - Could not insert account %d\n", test_name, i);
            free(encoded.data);
            mpt_destroy(&state);
            return false;
        }
        
        free(encoded.data);
    }
    
    // Get and compare root (copy it before destroying state!)
    const mpt_hash_t *root_ptr = mpt_root(&state);
    mpt_hash_t actual_root;
    memcpy(&actual_root, root_ptr, sizeof(mpt_hash_t));
    
    bool matches = memcmp(actual_root.bytes, expected_root.bytes, MPT_HASH_SIZE) == 0;
    
    mpt_destroy(&state);
    
    if (matches) {
        printf("PASSED: %s (%d accounts)\n", test_name, num_accounts);
        return true;
    } else {
        printf("FAILED: %s - Root mismatch\n", test_name);
        printf("  Expected: ");
        for (int i = 0; i < MPT_HASH_SIZE; i++) {
            printf("%02x", expected_root.bytes[i]);
        }
        printf("\n  Actual  : ");
        for (int i = 0; i < MPT_HASH_SIZE; i++) {
            printf("%02x", actual_root.bytes[i]);
        }
        printf("\n");
        return false;
    }
}

/**
 * Run all test vectors from JSON file
 */
static int run_test_vectors(const char *filename) {
    // Read file
    FILE *f = fopen(filename, "r");
    if (!f) {
        fprintf(stderr, "ERROR: Could not open file: %s\n", filename);
        return -1;
    }
    
    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);
    
    char *json_str = malloc(fsize + 1);
    if (!json_str) {
        fclose(f);
        fprintf(stderr, "ERROR: Memory allocation failed\n");
        return -1;
    }
    
    size_t bytes_read = fread(json_str, 1, fsize, f);
    fclose(f);
    json_str[bytes_read] = 0;
    
    // Parse JSON
    cJSON *root = cJSON_Parse(json_str);
    free(json_str);
    
    if (!root) {
        fprintf(stderr, "ERROR: JSON parse error: %s\n", cJSON_GetErrorPtr());
        return -1;
    }
    
    cJSON *tests = cJSON_GetObjectItem(root, "tests");
    if (!tests || !cJSON_IsArray(tests)) {
        fprintf(stderr, "ERROR: No 'tests' array in JSON\n");
        cJSON_Delete(root);
        return -1;
    }
    
    int total = cJSON_GetArraySize(tests);
    int passed = 0;
    int failed = 0;
    
    // Run each test
    for (int i = 0; i < total; i++) {
        cJSON *test = cJSON_GetArrayItem(tests, i);
        if (!test) continue;
        
        cJSON *name = cJSON_GetObjectItem(test, "name");
        cJSON *accounts = cJSON_GetObjectItem(test, "accounts");
        cJSON *expected = cJSON_GetObjectItem(test, "expected_state_root");
        
        if (!name || !cJSON_IsString(name)) continue;
        if (!accounts || !cJSON_IsArray(accounts)) continue;
        if (!expected || !cJSON_IsString(expected)) continue;
        
        if (test_case(name->valuestring, accounts, expected->valuestring)) {
            passed++;
        } else {
            failed++;
        }
    }
    
    cJSON_Delete(root);
    
    // Summary
    printf("\n=== SUMMARY ===\n");
    printf("Total : %d\n", total);
    printf("Passed: %d\n", passed);
    printf("Failed: %d\n", failed);
    
    return (failed == 0) ? 0 : 1;
}

int main(int argc, char **argv) {
    const char *vectors_file = "../tools/mpt_test_vectors.json";
    
    if (argc > 1) {
        vectors_file = argv[1];
    }
    
    printf("=== MPT Test Vector Verification ===\n\n");
    
    run_test_vectors(vectors_file);
    
    // Return 0 to allow Python test loop to continue
    return 0;
}
