/**
 * Verkle Cross-Validation Test
 *
 * Reads verkle_vectors.bin (generated by go-verkle reference implementation)
 * and validates that our C implementation produces identical root hashes.
 *
 * Tests both the in-memory tree and the flat updater backends.
 *
 * Vector format:
 *   [4B LE: num_scenarios]
 *   Per scenario:
 *     [2B LE: name_len] [name_len B: name]
 *     [1B: type]  0=build, 1=multiblock
 *     [4B LE: num_keys]
 *     Per key: [32B key] [32B value]
 *     [32B: expected_root]
 *     If type==1:
 *       [4B LE: num_blocks]
 *       Per block:
 *         [4B LE: num_ops]
 *         Per op: [32B key] [32B value]
 *         [32B: expected_root]
 */

#include "verkle.h"
#include "verkle_flat.h"
#include "pedersen.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* =========================================================================
 * Test Infrastructure
 * ========================================================================= */

static int tests_passed = 0;
static int tests_failed = 0;

#define ASSERT(cond, msg)                                              \
    do {                                                               \
        if (!(cond)) {                                                 \
            printf("  FAIL: %s (line %d)\n", msg, __LINE__);          \
            tests_failed++;                                            \
        } else {                                                       \
            tests_passed++;                                            \
        }                                                              \
    } while (0)

#define VAL_DIR  "/tmp/test_vcv_vals"
#define COMM_DIR "/tmp/test_vcv_comm"

static void cleanup(void) {
    system("rm -rf " VAL_DIR " " COMM_DIR);
}

/* =========================================================================
 * Binary Reader Helpers
 * ========================================================================= */

static uint16_t read_u16(FILE *fp) {
    uint8_t buf[2];
    if (fread(buf, 1, 2, fp) != 2) { fprintf(stderr, "read error\n"); exit(1); }
    return (uint16_t)buf[0] | ((uint16_t)buf[1] << 8);
}

static uint32_t read_u32(FILE *fp) {
    uint8_t buf[4];
    if (fread(buf, 1, 4, fp) != 4) { fprintf(stderr, "read error\n"); exit(1); }
    return (uint32_t)buf[0] | ((uint32_t)buf[1] << 8) |
           ((uint32_t)buf[2] << 16) | ((uint32_t)buf[3] << 24);
}

static void read_bytes(FILE *fp, uint8_t *out, size_t n) {
    if (fread(out, 1, n, fp) != n) { fprintf(stderr, "read error\n"); exit(1); }
}

/* =========================================================================
 * Root Hash Helpers
 * ========================================================================= */

static void tree_root(const verkle_tree_t *vt, uint8_t out[32]) {
    verkle_root_hash(vt, out);
}

static void flat_root(const verkle_flat_t *vf, uint8_t out[32]) {
    verkle_flat_root_hash(vf, out);
}

static void hex_str(const uint8_t *data, int len, char *out) {
    for (int i = 0; i < len; i++)
        sprintf(out + i * 2, "%02x", data[i]);
    out[len * 2] = '\0';
}

/* =========================================================================
 * Build Scenario — insert all keys, check root
 * ========================================================================= */

static void run_build_scenario(FILE *fp, const char *name) {
    uint32_t num_keys = read_u32(fp);

    /* Read keys and values */
    uint8_t (*keys)[32] = malloc(num_keys * 32);
    uint8_t (*vals)[32] = malloc(num_keys * 32);
    for (uint32_t i = 0; i < num_keys; i++) {
        read_bytes(fp, keys[i], 32);
        read_bytes(fp, vals[i], 32);
    }

    uint8_t expected_root[32];
    read_bytes(fp, expected_root, 32);

    /* --- Test 1: In-memory tree --- */
    verkle_tree_t *vt = verkle_create();
    for (uint32_t i = 0; i < num_keys; i++)
        verkle_set(vt, keys[i], vals[i]);

    uint8_t tree_hash[32];
    tree_root(vt, tree_hash);

    if (memcmp(tree_hash, expected_root, 32) != 0) {
        char exp[65], got[65];
        hex_str(expected_root, 32, exp);
        hex_str(tree_hash, 32, got);
        printf("  FAIL [tree] %s\n    expected: %s\n    got:      %s\n", name, exp, got);
        tests_failed++;
    } else {
        tests_passed++;
    }

    /* --- Test 2: Flat updater --- */
    cleanup();
    verkle_flat_t *vf = verkle_flat_create(VAL_DIR, COMM_DIR, 4096);
    verkle_flat_begin_block(vf, 1);
    for (uint32_t i = 0; i < num_keys; i++)
        verkle_flat_set(vf, keys[i], vals[i]);
    verkle_flat_commit_block(vf);

    uint8_t flat_hash[32];
    flat_root(vf, flat_hash);

    if (memcmp(flat_hash, expected_root, 32) != 0) {
        char exp[65], got[65];
        hex_str(expected_root, 32, exp);
        hex_str(flat_hash, 32, got);
        printf("  FAIL [flat] %s\n    expected: %s\n    got:      %s\n", name, exp, got);
        tests_failed++;
    } else {
        tests_passed++;
    }

    verkle_flat_destroy(vf);
    verkle_destroy(vt);
    free(keys);
    free(vals);
    cleanup();
}

/* =========================================================================
 * Multiblock Scenario — build initial, apply blocks, check roots
 * ========================================================================= */

static void run_multiblock_scenario(FILE *fp, const char *name) {
    /* Read initial state */
    uint32_t num_initial = read_u32(fp);
    uint8_t (*keys)[32] = malloc(num_initial * 32);
    uint8_t (*vals)[32] = malloc(num_initial * 32);
    for (uint32_t i = 0; i < num_initial; i++) {
        read_bytes(fp, keys[i], 32);
        read_bytes(fp, vals[i], 32);
    }

    uint8_t initial_root[32];
    read_bytes(fp, initial_root, 32);

    /* --- Test initial state with tree --- */
    verkle_tree_t *vt = verkle_create();
    for (uint32_t i = 0; i < num_initial; i++)
        verkle_set(vt, keys[i], vals[i]);

    uint8_t tree_hash[32];
    tree_root(vt, tree_hash);

    if (memcmp(tree_hash, initial_root, 32) != 0) {
        char exp[65], got[65];
        hex_str(initial_root, 32, exp);
        hex_str(tree_hash, 32, got);
        printf("  FAIL [tree initial] %s\n    expected: %s\n    got:      %s\n", name, exp, got);
        tests_failed++;
    } else {
        tests_passed++;
    }

    /* --- Test initial state with flat --- */
    cleanup();
    verkle_flat_t *vf = verkle_flat_create(VAL_DIR, COMM_DIR, 4096);
    verkle_flat_begin_block(vf, 0);
    for (uint32_t i = 0; i < num_initial; i++)
        verkle_flat_set(vf, keys[i], vals[i]);
    verkle_flat_commit_block(vf);

    uint8_t flat_hash[32];
    flat_root(vf, flat_hash);

    if (memcmp(flat_hash, initial_root, 32) != 0) {
        char exp[65], got[65];
        hex_str(initial_root, 32, exp);
        hex_str(flat_hash, 32, got);
        printf("  FAIL [flat initial] %s\n    expected: %s\n    got:      %s\n", name, exp, got);
        tests_failed++;
    } else {
        tests_passed++;
    }

    /* --- Process blocks --- */
    uint32_t num_blocks = read_u32(fp);

    for (uint32_t b = 0; b < num_blocks; b++) {
        uint32_t num_ops = read_u32(fp);
        uint8_t (*bkeys)[32] = malloc(num_ops * 32);
        uint8_t (*bvals)[32] = malloc(num_ops * 32);

        for (uint32_t i = 0; i < num_ops; i++) {
            read_bytes(fp, bkeys[i], 32);
            read_bytes(fp, bvals[i], 32);
        }

        uint8_t block_root[32];
        read_bytes(fp, block_root, 32);

        /* Apply to tree */
        for (uint32_t i = 0; i < num_ops; i++)
            verkle_set(vt, bkeys[i], bvals[i]);

        tree_root(vt, tree_hash);
        if (memcmp(tree_hash, block_root, 32) != 0) {
            char exp[65], got[65];
            hex_str(block_root, 32, exp);
            hex_str(tree_hash, 32, got);
            printf("  FAIL [tree block %u] %s\n    expected: %s\n    got:      %s\n",
                   b + 1, name, exp, got);
            tests_failed++;
        } else {
            tests_passed++;
        }

        /* Apply to flat */
        verkle_flat_begin_block(vf, b + 1);
        for (uint32_t i = 0; i < num_ops; i++)
            verkle_flat_set(vf, bkeys[i], bvals[i]);
        verkle_flat_commit_block(vf);

        flat_root(vf, flat_hash);
        if (memcmp(flat_hash, block_root, 32) != 0) {
            char exp[65], got[65];
            hex_str(block_root, 32, exp);
            hex_str(flat_hash, 32, got);
            printf("  FAIL [flat block %u] %s\n    expected: %s\n    got:      %s\n",
                   b + 1, name, exp, got);
            tests_failed++;
        } else {
            tests_passed++;
        }

        free(bkeys);
        free(bvals);
    }

    verkle_flat_destroy(vf);
    verkle_destroy(vt);
    free(keys);
    free(vals);
    cleanup();
}

/* =========================================================================
 * Main
 * ========================================================================= */

int main(int argc, char **argv) {
    const char *vecpath = "verkle_vectors.bin";
    if (argc > 1) vecpath = argv[1];

    /* Try default paths */
    FILE *fp = fopen(vecpath, "rb");
    if (!fp) {
        /* Try relative to source dir */
        fp = fopen("state/tests/verkle_vectors.bin", "rb");
    }
    if (!fp) {
        fprintf(stderr, "Cannot open %s (run gen_verkle_vectors first)\n", vecpath);
        return 1;
    }

    printf("=== Verkle Cross-Validation (go-verkle reference) ===\n\n"); fflush(stdout);
    pedersen_init();

    uint32_t num_scenarios = read_u32(fp);
    printf("Loading %u scenarios...\n\n", num_scenarios); fflush(stdout);

    for (uint32_t s = 0; s < num_scenarios; s++) {
        /* Read name */
        uint16_t name_len = read_u16(fp);
        char name[256] = {0};
        read_bytes(fp, (uint8_t *)name, name_len);
        name[name_len] = '\0';

        /* Read type */
        uint8_t typ;
        read_bytes(fp, &typ, 1);

        printf("Scenario %u: %s\n", s + 1, name); fflush(stdout);

        if (typ == 0) {
            run_build_scenario(fp, name);
        } else {
            run_multiblock_scenario(fp, name);
        }

        if (tests_failed > 0) {
            printf("\n!!! FAIL FAST: stopping after first failure !!!\n");
            break;
        }

        printf("  OK\n\n"); fflush(stdout);
    }

    fclose(fp);

    printf("=== Results: %d passed, %d failed ===\n",
           tests_passed, tests_failed);
    return tests_failed ? 1 : 0;
}
