#include "mpt.h"
#include "ih_hash_store.h"
#include "intermediate_hashes.h"  /* ih_cursor_t */
#include "hash.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <inttypes.h>
#include <assert.h>
#include <unistd.h>

/**
 * Cross-validation test: compare mpt_root() against Python's HexaryTrie
 * (reference Ethereum MPT implementation).
 *
 * Reads test vectors from mpt_vectors.bin generated by gen_mpt_vectors.py.
 * Scenario types: 0=build, 1=update, 2=multiblock.
 */

#define MPT_PATH "/tmp/test_mpt_cross_val.dat"

static int assertions = 0;
#define ASSERT(cond) do { \
    assertions++; \
    if (!(cond)) { \
        fprintf(stderr, "FAIL: %s:%d: %s\n", __FILE__, __LINE__, #cond); \
        abort(); \
    } \
} while(0)

static void print_hash(const char *label, const hash_t *h) {
    printf("    %s: ", label);
    for (int i = 0; i < 32; i++) printf("%02x", h->bytes[i]);
    printf("\n");
}

// ============================================================================
// Binary file reader helpers
// ============================================================================

static uint32_t read_u32(FILE *f) {
    uint8_t buf[4];
    ASSERT(fread(buf, 1, 4, f) == 4);
    return buf[0] | (buf[1] << 8) | (buf[2] << 16) | (buf[3] << 24);
}

static uint16_t read_u16(FILE *f) {
    uint8_t buf[2];
    ASSERT(fread(buf, 1, 2, f) == 2);
    return buf[0] | (buf[1] << 8);
}

static uint8_t read_u8(FILE *f) {
    uint8_t b;
    ASSERT(fread(&b, 1, 1, f) == 1);
    return b;
}

static void read_hash(FILE *f, hash_t *h) {
    ASSERT(fread(h->bytes, 1, 32, f) == 32);
}

typedef struct {
    uint8_t *keys;       // count * 32 bytes
    uint8_t *values;     // concatenated values
    size_t *val_offsets;
    size_t *val_lens;
    size_t count;
} kv_set_t;

static kv_set_t read_kv_set(FILE *f) {
    kv_set_t kv = {0};
    kv.count = read_u32(f);

    if (kv.count == 0) return kv;

    kv.keys = malloc(kv.count * 32);
    kv.val_offsets = malloc(kv.count * sizeof(size_t));
    kv.val_lens = malloc(kv.count * sizeof(size_t));

    // First pass: measure total value bytes
    size_t total_val = 0;
    long keys_start = ftell(f);
    for (size_t i = 0; i < kv.count; i++) {
        fseek(f, 32, SEEK_CUR);
        uint16_t vlen = read_u16(f);
        total_val += vlen;
        fseek(f, vlen, SEEK_CUR);
    }
    kv.values = malloc(total_val > 0 ? total_val : 1);

    // Second pass: read data
    fseek(f, keys_start, SEEK_SET);
    size_t voff = 0;
    for (size_t i = 0; i < kv.count; i++) {
        ASSERT(fread(kv.keys + i * 32, 1, 32, f) == 32);
        uint16_t vlen = read_u16(f);
        kv.val_lens[i] = vlen;
        kv.val_offsets[i] = voff;
        if (vlen > 0)
            ASSERT(fread(kv.values + voff, 1, vlen, f) == vlen);
        voff += vlen;
    }
    return kv;
}

static void free_kv_set(kv_set_t *kv) {
    free(kv->keys);
    free(kv->values);
    free(kv->val_offsets);
    free(kv->val_lens);
    memset(kv, 0, sizeof(*kv));
}

// ============================================================================
// Dirty set reader
// ============================================================================

typedef struct {
    uint8_t *keys;
    uint8_t *val_buf;
    size_t *val_offsets;
    size_t *vlens;
    uint32_t count;
} dirty_set_t;

static dirty_set_t read_dirty_set(FILE *f) {
    dirty_set_t ds = {0};
    ds.count = read_u32(f);
    if (ds.count == 0) return ds;

    ds.keys = malloc(ds.count * 32);
    ds.val_offsets = malloc(ds.count * sizeof(size_t));
    ds.vlens = malloc(ds.count * sizeof(size_t));

    // First pass: measure total value bytes
    size_t total = 0;
    long start = ftell(f);
    for (uint32_t d = 0; d < ds.count; d++) {
        fseek(f, 32, SEEK_CUR);
        uint16_t vlen = read_u16(f);
        total += vlen;
        fseek(f, vlen, SEEK_CUR);
    }
    ds.val_buf = malloc(total > 0 ? total : 1);

    // Second pass: read
    fseek(f, start, SEEK_SET);
    size_t off = 0;
    for (uint32_t d = 0; d < ds.count; d++) {
        ASSERT(fread(ds.keys + d * 32, 1, 32, f) == 32);
        uint16_t vlen = read_u16(f);
        ds.vlens[d] = vlen;
        ds.val_offsets[d] = off;
        if (vlen > 0)
            ASSERT(fread(ds.val_buf + off, 1, vlen, f) == vlen);
        off += vlen;
    }
    return ds;
}

static void free_dirty_set(dirty_set_t *ds) {
    free(ds->keys);
    free(ds->val_buf);
    free(ds->val_offsets);
    free(ds->vlens);
    memset(ds, 0, sizeof(*ds));
}

// ============================================================================
// MPT helpers
// ============================================================================

/* Insert all entries from a kv_set into the mpt */
static void mpt_put_kv_set(mpt_t *m, const kv_set_t *kv) {
    for (size_t i = 0; i < kv->count; i++) {
        bool ok = mpt_put(m, kv->keys + i * 32,
                          kv->values + kv->val_offsets[i],
                          (uint8_t)kv->val_lens[i]);
        ASSERT(ok);
    }
}

/* Apply dirty set: put (vlen > 0) or delete (vlen == 0) */
static void mpt_apply_dirty(mpt_t *m, const dirty_set_t *ds) {
    for (uint32_t d = 0; d < ds->count; d++) {
        const uint8_t *dk = ds->keys + d * 32;
        if (ds->vlens[d] > 0) {
            bool ok = mpt_put(m, dk,
                              ds->val_buf + ds->val_offsets[d],
                              (uint8_t)ds->vlens[d]);
            ASSERT(ok);
        } else {
            mpt_delete(m, dk);
        }
    }
}

// ============================================================================
// IH Hash Store Helpers: merged state + cursor
// ============================================================================

#define IHS_DIR "/tmp/test_ihs_crossval"

typedef struct {
    uint8_t *keys;        /* count * 32, sorted */
    uint8_t *val_buf;
    size_t  *val_offsets;
    size_t  *val_lens;
    size_t   count;
    size_t   val_used;
    size_t   val_cap;
    size_t   key_cap;
} merged_state_t;

static void merged_init(merged_state_t *ms) {
    memset(ms, 0, sizeof(*ms));
}

static void merged_free(merged_state_t *ms) {
    free(ms->keys);
    free(ms->val_buf);
    free(ms->val_offsets);
    free(ms->val_lens);
    memset(ms, 0, sizeof(*ms));
}

/* Build merged state from a kv_set (already sorted) */
static void merged_from_kv(merged_state_t *ms, const kv_set_t *kv) {
    merged_free(ms);
    ms->count = kv->count;
    ms->key_cap = kv->count > 0 ? kv->count : 8;
    ms->keys = malloc(ms->key_cap * 32);
    ms->val_offsets = malloc(ms->key_cap * sizeof(size_t));
    ms->val_lens = malloc(ms->key_cap * sizeof(size_t));

    /* Compute total value bytes */
    size_t total = 0;
    for (size_t i = 0; i < kv->count; i++)
        total += kv->val_lens[i];

    ms->val_cap = total > 0 ? total : 64;
    ms->val_buf = malloc(ms->val_cap);
    ms->val_used = 0;

    for (size_t i = 0; i < kv->count; i++) {
        memcpy(ms->keys + i * 32, kv->keys + i * 32, 32);
        ms->val_offsets[i] = ms->val_used;
        ms->val_lens[i] = kv->val_lens[i];
        if (kv->val_lens[i] > 0) {
            memcpy(ms->val_buf + ms->val_used,
                   kv->values + kv->val_offsets[i], kv->val_lens[i]);
            ms->val_used += kv->val_lens[i];
        }
    }
}

/* Binary search: find index of key or insertion point */
static size_t merged_find(const merged_state_t *ms, const uint8_t *key) {
    size_t lo = 0, hi = ms->count;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        if (memcmp(ms->keys + mid * 32, key, 32) < 0)
            lo = mid + 1;
        else
            hi = mid;
    }
    return lo;
}

/* Apply a dirty set to merged state (insert/update/delete) */
static void merged_apply_dirty(merged_state_t *ms, const dirty_set_t *ds) {
    for (uint32_t d = 0; d < ds->count; d++) {
        const uint8_t *dk = ds->keys + d * 32;
        size_t vlen = ds->vlens[d];
        const uint8_t *val = ds->val_buf + ds->val_offsets[d];

        size_t pos = merged_find(ms, dk);
        bool exists = (pos < ms->count && memcmp(ms->keys + pos * 32, dk, 32) == 0);

        if (vlen == 0) {
            /* Delete */
            if (exists) {
                memmove(ms->keys + pos * 32, ms->keys + (pos + 1) * 32,
                        (ms->count - pos - 1) * 32);
                memmove(ms->val_offsets + pos, ms->val_offsets + (pos + 1),
                        (ms->count - pos - 1) * sizeof(size_t));
                memmove(ms->val_lens + pos, ms->val_lens + (pos + 1),
                        (ms->count - pos - 1) * sizeof(size_t));
                ms->count--;
            }
        } else if (exists) {
            /* Update value in place (append to val_buf) */
            if (ms->val_used + vlen > ms->val_cap) {
                ms->val_cap = (ms->val_cap + vlen) * 2;
                ms->val_buf = realloc(ms->val_buf, ms->val_cap);
            }
            ms->val_offsets[pos] = ms->val_used;
            ms->val_lens[pos] = vlen;
            memcpy(ms->val_buf + ms->val_used, val, vlen);
            ms->val_used += vlen;
        } else {
            /* Insert at pos */
            ms->count++;
            if (ms->count > ms->key_cap) {
                ms->key_cap *= 2;
                ms->keys = realloc(ms->keys, ms->key_cap * 32);
                ms->val_offsets = realloc(ms->val_offsets, ms->key_cap * sizeof(size_t));
                ms->val_lens = realloc(ms->val_lens, ms->key_cap * sizeof(size_t));
            }
            memmove(ms->keys + (pos + 1) * 32, ms->keys + pos * 32,
                    (ms->count - pos - 1) * 32);
            memmove(ms->val_offsets + (pos + 1), ms->val_offsets + pos,
                    (ms->count - pos - 1) * sizeof(size_t));
            memmove(ms->val_lens + (pos + 1), ms->val_lens + pos,
                    (ms->count - pos - 1) * sizeof(size_t));

            memcpy(ms->keys + pos * 32, dk, 32);
            if (ms->val_used + vlen > ms->val_cap) {
                ms->val_cap = (ms->val_cap + vlen) * 2;
                ms->val_buf = realloc(ms->val_buf, ms->val_cap);
            }
            ms->val_offsets[pos] = ms->val_used;
            ms->val_lens[pos] = vlen;
            memcpy(ms->val_buf + ms->val_used, val, vlen);
            ms->val_used += vlen;
        }
    }
}

/* Cursor over merged state */
typedef struct {
    const merged_state_t *ms;
    size_t pos;
} merged_cursor_ctx_t;

static bool mc_seek(void *ctx, const uint8_t *seek_key, size_t key_len) {
    merged_cursor_ctx_t *mc = ctx;
    (void)key_len;
    mc->pos = merged_find(mc->ms, seek_key);
    return mc->pos < mc->ms->count;
}

static bool mc_next(void *ctx) {
    merged_cursor_ctx_t *mc = ctx;
    if (mc->pos < mc->ms->count) mc->pos++;
    return mc->pos < mc->ms->count;
}

static bool mc_valid(void *ctx) {
    merged_cursor_ctx_t *mc = ctx;
    return mc->pos < mc->ms->count;
}

static const uint8_t *mc_key(void *ctx, size_t *out_len) {
    merged_cursor_ctx_t *mc = ctx;
    if (mc->pos >= mc->ms->count) return NULL;
    *out_len = 32;
    return mc->ms->keys + mc->pos * 32;
}

static const uint8_t *mc_value(void *ctx, size_t *out_len) {
    merged_cursor_ctx_t *mc = ctx;
    if (mc->pos >= mc->ms->count) return NULL;
    *out_len = mc->ms->val_lens[mc->pos];
    return mc->ms->val_buf + mc->ms->val_offsets[mc->pos];
}

static ih_cursor_t make_merged_cursor(merged_cursor_ctx_t *mc) {
    ih_cursor_t c;
    c.ctx = mc;
    c.seek = mc_seek;
    c.next = mc_next;
    c.valid = mc_valid;
    c.key = mc_key;
    c.value = mc_value;
    return c;
}

/* Build pointer arrays for ihs_build */
static void make_kv_ptrs(const kv_set_t *kv,
                          const uint8_t **key_ptrs,
                          const uint8_t **val_ptrs,
                          uint16_t *vlens) {
    for (size_t i = 0; i < kv->count; i++) {
        key_ptrs[i] = kv->keys + i * 32;
        val_ptrs[i] = kv->values + kv->val_offsets[i];
        vlens[i] = (uint16_t)kv->val_lens[i];
    }
}

/* Build dirty key/val pointer arrays for ih_update/ihs_update */
static void make_dirty_ptrs(const dirty_set_t *ds,
                             const uint8_t **key_ptrs,
                             const uint8_t **val_ptrs,
                             size_t *vlens) {
    for (uint32_t i = 0; i < ds->count; i++) {
        key_ptrs[i] = ds->keys + i * 32;
        val_ptrs[i] = ds->val_buf + ds->val_offsets[i];
        vlens[i] = ds->vlens[i];
    }
}

/* Sort dirty pointer arrays by key (ih_update requires sorted dirty keys) */
static void sort_dirty_ptrs(const uint8_t **key_ptrs,
                             const uint8_t **val_ptrs,
                             size_t *vlens,
                             size_t count) {
    /* Simple insertion sort — dirty sets are small */
    for (size_t i = 1; i < count; i++) {
        const uint8_t *tk = key_ptrs[i];
        const uint8_t *tv = val_ptrs[i];
        size_t tl = vlens[i];
        size_t j = i;
        while (j > 0 && memcmp(key_ptrs[j - 1], tk, 32) > 0) {
            key_ptrs[j] = key_ptrs[j - 1];
            val_ptrs[j] = val_ptrs[j - 1];
            vlens[j] = vlens[j - 1];
            j--;
        }
        key_ptrs[j] = tk;
        val_ptrs[j] = tv;
        vlens[j] = tl;
    }
}

static void remove_dir(const char *dir) {
    char cmd[256];
    snprintf(cmd, sizeof(cmd), "rm -rf %s", dir);
    (void)system(cmd);
}

// ============================================================================
// Main
// ============================================================================

int main(void) {
    printf("=== MPT Cross-Validation (Python HexaryTrie reference) ===\n\n");

    FILE *f = fopen("database/tests/mpt_vectors.bin", "rb");
    if (!f)
        f = fopen("../database/tests/mpt_vectors.bin", "rb");
    if (!f) {
        fprintf(stderr, "ERROR: mpt_vectors.bin not found.\n"
                "Run: ./venv/bin/python3 database/tests/gen_mpt_vectors.py\n");
        return 1;
    }

    uint32_t num_scenarios = read_u32(f);
    printf("Loaded %u scenarios from mpt_vectors.bin\n\n", num_scenarios);

    int build_pass = 0, update_pass = 0, multiblock_pass = 0;

    for (uint32_t s = 0; s < num_scenarios; s++) {
        uint8_t stype = read_u8(f);

        if (stype == 0) {
            // ---- Build scenario ----
            kv_set_t kv = read_kv_set(f);
            hash_t expected;
            read_hash(f, &expected);

            printf("Scenario %u [BUILD]: %zu keys\n", s + 1, kv.count);

            unlink(MPT_PATH);
            mpt_t *m = mpt_create(MPT_PATH);
            ASSERT(m != NULL);

            mpt_put_kv_set(m, &kv);
            hash_t root = mpt_root(m);

            print_hash("expected", &expected);
            print_hash("got     ", &root);
            ASSERT(hash_equal(&root, &expected));

            /* --- IH hash_store: build and compare --- */
            remove_dir(IHS_DIR);
            ihs_state_t *ihs = ihs_create(IHS_DIR);
            ASSERT(ihs != NULL);

            if (kv.count > 0) {
                const uint8_t **kptrs = malloc(kv.count * sizeof(uint8_t *));
                const uint8_t **vptrs = malloc(kv.count * sizeof(uint8_t *));
                uint16_t *vlens = malloc(kv.count * sizeof(uint16_t));
                make_kv_ptrs(&kv, kptrs, vptrs, vlens);

                hash_t ihs_root_h = ihs_build(ihs, kptrs, vptrs, vlens, kv.count);
                print_hash("ihs_root", &ihs_root_h);
                ASSERT(hash_equal(&ihs_root_h, &expected));

                free(kptrs); free(vptrs); free(vlens);
            } else {
                hash_t ihs_root_h = ihs_build(ihs, NULL, NULL, NULL, 0);
                ASSERT(hash_equal(&ihs_root_h, &expected));
            }

            ihs_destroy(ihs);
            remove_dir(IHS_DIR);

            mpt_close(m);
            unlink(MPT_PATH);
            free_kv_set(&kv);
            build_pass++;
            printf("    PASS\n\n");

        } else if (stype == 1) {
            // ---- Update scenario (single dirty block) ----
            kv_set_t initial = read_kv_set(f);
            hash_t initial_root;
            read_hash(f, &initial_root);

            dirty_set_t ds = read_dirty_set(f);
            hash_t expected_after;
            read_hash(f, &expected_after);

            printf("Scenario %u [UPDATE]: %zu initial + %u dirty\n",
                   s + 1, initial.count, ds.count);

            unlink(MPT_PATH);
            mpt_t *m = mpt_create(MPT_PATH);
            ASSERT(m != NULL);

            // Insert initial keys and verify initial root
            mpt_put_kv_set(m, &initial);
            hash_t built_root = mpt_root(m);
            ASSERT(hash_equal(&built_root, &initial_root));

            // Apply dirty ops and verify updated root
            mpt_apply_dirty(m, &ds);
            hash_t update_root = mpt_root(m);

            print_hash("expected", &expected_after);
            print_hash("got     ", &update_root);
            ASSERT(hash_equal(&update_root, &expected_after));

            /* --- IH: build initial, then update (both compact_art + hash_store) --- */
            {
                const uint8_t **kptrs = NULL, **vptrs = NULL;
                uint16_t *vlens16 = NULL;
                if (initial.count > 0) {
                    kptrs = malloc(initial.count * sizeof(uint8_t *));
                    vptrs = malloc(initial.count * sizeof(uint8_t *));
                    vlens16 = malloc(initial.count * sizeof(uint16_t));
                    make_kv_ptrs(&initial, kptrs, vptrs, vlens16);
                }

                /* compact_art IH */
                ih_state_t *ih = ih_create();
                ASSERT(ih != NULL);
                hash_t ih_init = ih_build(ih, kptrs, vptrs, vlens16, initial.count);
                ASSERT(hash_equal(&ih_init, &initial_root));

                /* hash_store IH */
                remove_dir(IHS_DIR);
                ihs_state_t *ihs = ihs_create(IHS_DIR);
                ASSERT(ihs != NULL);
                hash_t ihs_init = ihs_build(ihs, kptrs, vptrs, vlens16, initial.count);
                ASSERT(hash_equal(&ihs_init, &initial_root));

                free(kptrs); free(vptrs); free(vlens16);

                /* Build merged state (initial + dirty) for cursor */
                merged_state_t ms;
                merged_init(&ms);
                merged_from_kv(&ms, &initial);
                merged_apply_dirty(&ms, &ds);

                /* Dirty pointer arrays */
                const uint8_t **dkptrs = malloc(ds.count * sizeof(uint8_t *));
                const uint8_t **dvptrs = malloc(ds.count * sizeof(uint8_t *));
                size_t *dvlens = malloc(ds.count * sizeof(size_t));
                make_dirty_ptrs(&ds, dkptrs, dvptrs, dvlens);
                sort_dirty_ptrs(dkptrs, dvptrs, dvlens, ds.count);

                /* compact_art ih_update */
                merged_cursor_ctx_t mc1 = { .ms = &ms, .pos = 0 };
                ih_cursor_t cur1 = make_merged_cursor(&mc1);
                hash_t ih_upd = ih_update(ih, dkptrs, dvptrs, dvlens, ds.count, &cur1);
                print_hash("ih_upd  ", &ih_upd);
                ASSERT(hash_equal(&ih_upd, &expected_after));

                /* hash_store ihs_update */
                merged_cursor_ctx_t mc2 = { .ms = &ms, .pos = 0 };
                ih_cursor_t cur2 = make_merged_cursor(&mc2);
                hash_t ihs_upd = ihs_update(ihs, dkptrs, dvptrs, dvlens, ds.count, &cur2);
                print_hash("ihs_upd ", &ihs_upd);
                ASSERT(hash_equal(&ihs_upd, &expected_after));

                free(dkptrs); free(dvptrs); free(dvlens);
                merged_free(&ms);
                ih_destroy(ih);
                ihs_destroy(ihs);
                remove_dir(IHS_DIR);
            }

            mpt_close(m);
            unlink(MPT_PATH);
            free_dirty_set(&ds);
            free_kv_set(&initial);
            update_pass++;
            printf("    PASS\n\n");

        } else if (stype == 2) {
            // ---- Multi-block scenario ----
            kv_set_t initial = read_kv_set(f);
            hash_t initial_root;
            read_hash(f, &initial_root);

            uint32_t num_blocks = read_u32(f);

            printf("Scenario %u [MULTIBLOCK]: %zu initial, %u blocks\n",
                   s + 1, initial.count, num_blocks);

            unlink(MPT_PATH);
            mpt_t *m = mpt_create(MPT_PATH);
            ASSERT(m != NULL);

            // Build initial state
            mpt_put_kv_set(m, &initial);
            hash_t built_root = mpt_root(m);
            ASSERT(hash_equal(&built_root, &initial_root));

            /* --- IH hash_store: build initial, then update each block --- */
            remove_dir(IHS_DIR);
            ihs_state_t *ihs = ihs_create(IHS_DIR);
            ASSERT(ihs != NULL);

            {
                const uint8_t **kptrs = NULL, **vptrs = NULL;
                uint16_t *vlens16 = NULL;
                if (initial.count > 0) {
                    kptrs = malloc(initial.count * sizeof(uint8_t *));
                    vptrs = malloc(initial.count * sizeof(uint8_t *));
                    vlens16 = malloc(initial.count * sizeof(uint16_t));
                    make_kv_ptrs(&initial, kptrs, vptrs, vlens16);
                }
                hash_t ihs_init = ihs_build(ihs, kptrs, vptrs, vlens16, initial.count);
                ASSERT(hash_equal(&ihs_init, &initial_root));
                free(kptrs); free(vptrs); free(vlens16);
            }

            merged_state_t ms;
            merged_init(&ms);
            merged_from_kv(&ms, &initial);

            for (uint32_t blk = 0; blk < num_blocks; blk++) {
                dirty_set_t ds = read_dirty_set(f);
                hash_t expected;
                read_hash(f, &expected);

                /* MPT */
                mpt_apply_dirty(m, &ds);
                hash_t root = mpt_root(m);

                printf("  block %u/%u: %u dirty, %" PRIu64 " total keys\n",
                       blk + 1, num_blocks, ds.count, mpt_size(m));

                print_hash("expected", &expected);
                print_hash("mpt     ", &root);
                ASSERT(hash_equal(&root, &expected));

                /* IH hash_store: incremental update */
                merged_apply_dirty(&ms, &ds);

                const uint8_t **dkptrs = malloc(ds.count * sizeof(uint8_t *));
                const uint8_t **dvptrs = malloc(ds.count * sizeof(uint8_t *));
                size_t *dvlens = malloc(ds.count * sizeof(size_t));
                make_dirty_ptrs(&ds, dkptrs, dvptrs, dvlens);
                sort_dirty_ptrs(dkptrs, dvptrs, dvlens, ds.count);

                merged_cursor_ctx_t mc_ctx = { .ms = &ms, .pos = 0 };
                ih_cursor_t cursor = make_merged_cursor(&mc_ctx);

                hash_t ihs_root_h = ihs_update(ihs, dkptrs, dvptrs, dvlens, ds.count, &cursor);
                print_hash("ihs     ", &ihs_root_h);
                ASSERT(hash_equal(&ihs_root_h, &expected));

                free(dkptrs); free(dvptrs); free(dvlens);
                free_dirty_set(&ds);
            }

            merged_free(&ms);
            ihs_destroy(ihs);
            remove_dir(IHS_DIR);

            mpt_close(m);
            unlink(MPT_PATH);
            free_kv_set(&initial);
            multiblock_pass++;
            printf("    PASS\n\n");

        } else {
            fprintf(stderr, "ERROR: unknown scenario type %u\n", stype);
            return 1;
        }
    }

    fclose(f);

    printf("=== CROSS-VALIDATION COMPLETE ===\n");
    printf("  Build scenarios:      %d passed\n", build_pass);
    printf("  Update scenarios:     %d passed\n", update_pass);
    printf("  Multi-block scenarios: %d passed\n", multiblock_pass);
    printf("  Total assertions:     %d\n", assertions);
    return 0;
}
