#include "intermediate_hashes.h"
#include "hash.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

/**
 * Cross-validation test: compare ih_build/ih_update roots against
 * Python's HexaryTrie (reference Ethereum MPT implementation).
 *
 * Reads test vectors from mpt_vectors.bin generated by gen_mpt_vectors.py.
 */

static int assertions = 0;
#define ASSERT(cond) do { \
    assertions++; \
    if (!(cond)) { \
        fprintf(stderr, "FAIL: %s:%d: %s\n", __FILE__, __LINE__, #cond); \
        abort(); \
    } \
} while(0)

static void print_hash(const char *label, const hash_t *h) {
    printf("    %s: ", label);
    for (int i = 0; i < 32; i++) printf("%02x", h->bytes[i]);
    printf("\n");
}

// ============================================================================
// Binary file reader helpers
// ============================================================================

static uint32_t read_u32(FILE *f) {
    uint8_t buf[4];
    ASSERT(fread(buf, 1, 4, f) == 4);
    return buf[0] | (buf[1] << 8) | (buf[2] << 16) | (buf[3] << 24);
}

static uint16_t read_u16(FILE *f) {
    uint8_t buf[2];
    ASSERT(fread(buf, 1, 2, f) == 2);
    return buf[0] | (buf[1] << 8);
}

static uint8_t read_u8(FILE *f) {
    uint8_t b;
    ASSERT(fread(&b, 1, 1, f) == 1);
    return b;
}

static void read_hash(FILE *f, hash_t *h) {
    ASSERT(fread(h->bytes, 1, 32, f) == 32);
}

typedef struct {
    uint8_t *keys;      // count * 32 bytes
    uint8_t *values;    // concatenated values
    size_t *val_offsets; // offset into values for each entry
    size_t *val_lens;   // length of each value
    size_t count;
} kv_set_t;

static kv_set_t read_kv_set(FILE *f) {
    kv_set_t kv = {0};
    kv.count = read_u32(f);

    if (kv.count == 0) return kv;

    kv.keys = malloc(kv.count * 32);
    kv.val_offsets = malloc(kv.count * sizeof(size_t));
    kv.val_lens = malloc(kv.count * sizeof(size_t));

    // First pass: read and measure total value bytes
    size_t total_val = 0;
    long keys_start = ftell(f);

    for (size_t i = 0; i < kv.count; i++) {
        fseek(f, 32, SEEK_CUR); // skip key
        uint16_t vlen = read_u16(f);
        total_val += vlen;
        fseek(f, vlen, SEEK_CUR); // skip value
    }

    kv.values = malloc(total_val > 0 ? total_val : 1);

    // Second pass: read data
    fseek(f, keys_start, SEEK_SET);
    size_t voff = 0;
    for (size_t i = 0; i < kv.count; i++) {
        ASSERT(fread(kv.keys + i * 32, 1, 32, f) == 32);
        uint16_t vlen = read_u16(f);
        kv.val_lens[i] = vlen;
        kv.val_offsets[i] = voff;
        if (vlen > 0) {
            ASSERT(fread(kv.values + voff, 1, vlen, f) == vlen);
        }
        voff += vlen;
    }

    return kv;
}

static void free_kv_set(kv_set_t *kv) {
    free(kv->keys);
    free(kv->values);
    free(kv->val_offsets);
    free(kv->val_lens);
    memset(kv, 0, sizeof(*kv));
}

// ============================================================================
// Mock Cursor (for ih_update tests)
// ============================================================================

typedef struct {
    const uint8_t *const *keys;
    const uint8_t *const *vals;
    const size_t *vlens;
    size_t count;
    size_t pos;
} mock_cursor_ctx_t;

static bool mock_seek(void *ctx, const uint8_t *seek_key, size_t key_len) {
    mock_cursor_ctx_t *mc = ctx;
    (void)key_len;
    size_t lo = 0, hi = mc->count;
    while (lo < hi) {
        size_t mid = lo + (hi - lo) / 2;
        if (memcmp(mc->keys[mid], seek_key, 32) < 0)
            lo = mid + 1;
        else
            hi = mid;
    }
    mc->pos = lo;
    return lo < mc->count;
}

static bool mock_next(void *ctx) {
    mock_cursor_ctx_t *mc = ctx;
    if (mc->pos < mc->count) mc->pos++;
    return mc->pos < mc->count;
}

static bool mock_valid(void *ctx) {
    mock_cursor_ctx_t *mc = ctx;
    return mc->pos < mc->count;
}

static const uint8_t *mock_key(void *ctx, size_t *out_len) {
    mock_cursor_ctx_t *mc = ctx;
    if (mc->pos >= mc->count) return NULL;
    *out_len = 32;
    return mc->keys[mc->pos];
}

static const uint8_t *mock_value(void *ctx, size_t *out_len) {
    mock_cursor_ctx_t *mc = ctx;
    if (mc->pos >= mc->count) return NULL;
    *out_len = mc->vlens[mc->pos];
    return mc->vals[mc->pos];
}

// ============================================================================
// Sort helper (for merging dirty keys into cursor)
// ============================================================================

typedef struct { const uint8_t *key; const uint8_t *val; size_t vlen; } kv_entry_t;

static int kv_cmp(const void *a, const void *b) {
    return memcmp(((kv_entry_t *)a)->key, ((kv_entry_t *)b)->key, 32);
}

// ============================================================================
// Main
// ============================================================================

int main(void) {
    printf("=== MPT Cross-Validation (Python HexaryTrie reference) ===\n\n");

    FILE *f = fopen("database/tests/mpt_vectors.bin", "rb");
    if (!f) {
        f = fopen("../database/tests/mpt_vectors.bin", "rb");
    }
    if (!f) {
        fprintf(stderr, "ERROR: mpt_vectors.bin not found.\n"
                "Run: ./venv/bin/python3 database/tests/gen_mpt_vectors.py\n");
        return 1;
    }

    uint32_t num_scenarios = read_u32(f);
    printf("Loaded %u scenarios from mpt_vectors.bin\n\n", num_scenarios);

    int build_pass = 0, update_pass = 0;

    for (uint32_t s = 0; s < num_scenarios; s++) {
        uint8_t stype = read_u8(f);

        if (stype == 0) {
            // Build scenario
            kv_set_t kv = read_kv_set(f);
            hash_t expected;
            read_hash(f, &expected);

            printf("Scenario %u [BUILD]: %zu keys\n", s + 1, kv.count);

            ih_state_t *ih = ih_create();
            ASSERT(ih != NULL);

            if (kv.count == 0) {
                hash_t root = ih_build(ih, NULL, NULL, NULL, 0);
                print_hash("expected", &expected);
                print_hash("got     ", &root);
                ASSERT(hash_equal(&root, &expected));
            } else {
                // Build pointer arrays
                const uint8_t **key_ptrs = malloc(kv.count * sizeof(uint8_t *));
                const uint8_t **val_ptrs = malloc(kv.count * sizeof(uint8_t *));
                uint16_t *vlens = malloc(kv.count * sizeof(uint16_t));

                for (size_t i = 0; i < kv.count; i++) {
                    key_ptrs[i] = kv.keys + i * 32;
                    val_ptrs[i] = kv.values + kv.val_offsets[i];
                    vlens[i] = (uint16_t)kv.val_lens[i];
                }

                hash_t root = ih_build(ih, key_ptrs, val_ptrs, vlens, kv.count);
                print_hash("expected", &expected);
                print_hash("got     ", &root);
                ASSERT(hash_equal(&root, &expected));

                free(key_ptrs);
                free(val_ptrs);
                free(vlens);
            }

            ih_destroy(ih);
            free_kv_set(&kv);
            build_pass++;
            printf("    PASS\n\n");

        } else {
            // Update scenario
            kv_set_t initial = read_kv_set(f);
            hash_t initial_root;
            read_hash(f, &initial_root);

            // Read dirty keys
            uint32_t num_dirty = read_u32(f);
            uint8_t *dirty_keys = malloc(num_dirty * 32);
            uint8_t *dirty_val_buf = NULL;
            size_t dirty_val_total = 0;
            size_t *dirty_val_offsets = malloc(num_dirty * sizeof(size_t));
            size_t *dirty_vlens = malloc(num_dirty * sizeof(size_t));

            // First pass: measure
            long dirty_start = ftell(f);
            for (uint32_t d = 0; d < num_dirty; d++) {
                fseek(f, 32, SEEK_CUR);
                uint16_t vlen = read_u16(f);
                dirty_val_total += vlen;
                fseek(f, vlen, SEEK_CUR);
            }
            dirty_val_buf = malloc(dirty_val_total > 0 ? dirty_val_total : 1);

            // Second pass: read
            fseek(f, dirty_start, SEEK_SET);
            size_t dvoff = 0;
            for (uint32_t d = 0; d < num_dirty; d++) {
                ASSERT(fread(dirty_keys + d * 32, 1, 32, f) == 32);
                uint16_t vlen = read_u16(f);
                dirty_vlens[d] = vlen;
                dirty_val_offsets[d] = dvoff;
                if (vlen > 0) {
                    ASSERT(fread(dirty_val_buf + dvoff, 1, vlen, f) == vlen);
                }
                dvoff += vlen;
            }

            hash_t expected_after;
            read_hash(f, &expected_after);

            printf("Scenario %u [UPDATE]: %zu initial + %u dirty\n",
                   s + 1, initial.count, num_dirty);

            // Step 1: Build initial trie
            ih_state_t *ih = ih_create();
            ASSERT(ih != NULL);

            const uint8_t **init_key_ptrs = malloc(initial.count * sizeof(uint8_t *));
            const uint8_t **init_val_ptrs = malloc(initial.count * sizeof(uint8_t *));
            uint16_t *init_vlens = malloc(initial.count * sizeof(uint16_t));

            for (size_t i = 0; i < initial.count; i++) {
                init_key_ptrs[i] = initial.keys + i * 32;
                init_val_ptrs[i] = initial.values + initial.val_offsets[i];
                init_vlens[i] = (uint16_t)initial.val_lens[i];
            }

            hash_t built_root = ih_build(ih, init_key_ptrs, init_val_ptrs,
                                         init_vlens, initial.count);
            ASSERT(hash_equal(&built_root, &initial_root));

            // Step 2: Build merged cursor state (initial + dirty applied)
            // Merge: start with initial, apply dirty (update/insert/delete)
            kv_entry_t *merged = malloc((initial.count + num_dirty) * sizeof(kv_entry_t));
            size_t merged_count = 0;

            // Add all initial entries
            for (size_t i = 0; i < initial.count; i++) {
                merged[merged_count].key = initial.keys + i * 32;
                merged[merged_count].val = initial.values + initial.val_offsets[i];
                merged[merged_count].vlen = initial.val_lens[i];
                merged_count++;
            }

            // Apply dirty: update existing or add new
            for (uint32_t d = 0; d < num_dirty; d++) {
                const uint8_t *dk = dirty_keys + d * 32;
                const uint8_t *dv = dirty_val_buf + dirty_val_offsets[d];
                size_t dvl = dirty_vlens[d];

                // Find in merged
                bool found = false;
                for (size_t i = 0; i < merged_count; i++) {
                    if (memcmp(merged[i].key, dk, 32) == 0) {
                        if (dvl == 0) {
                            // Delete: remove by swapping with last
                            merged[i] = merged[merged_count - 1];
                            merged_count--;
                        } else {
                            merged[i].val = dv;
                            merged[i].vlen = dvl;
                        }
                        found = true;
                        break;
                    }
                }
                if (!found && dvl > 0) {
                    // Insert
                    merged[merged_count].key = dk;
                    merged[merged_count].val = dv;
                    merged[merged_count].vlen = dvl;
                    merged_count++;
                }
            }

            // Sort merged by key
            qsort(merged, merged_count, sizeof(kv_entry_t), kv_cmp);

            // Build cursor arrays
            const uint8_t **cursor_keys = malloc(merged_count * sizeof(uint8_t *));
            const uint8_t **cursor_vals = malloc(merged_count * sizeof(uint8_t *));
            size_t *cursor_vlens = malloc(merged_count * sizeof(size_t));
            for (size_t i = 0; i < merged_count; i++) {
                cursor_keys[i] = merged[i].key;
                cursor_vals[i] = merged[i].val;
                cursor_vlens[i] = merged[i].vlen;
            }

            mock_cursor_ctx_t mc = {
                cursor_keys, cursor_vals, cursor_vlens,
                merged_count, 0
            };
            ih_cursor_t cursor = {
                .ctx = &mc,
                .seek = mock_seek,
                .next = mock_next,
                .valid = mock_valid,
                .key = mock_key,
                .value = mock_value,
            };

            // Step 3: Build dirty key arrays and sort by key
            //         (ih_update requires dirty keys in sorted ascending order)
            typedef struct { const uint8_t *key; const uint8_t *val; size_t vlen; } dk_entry_t;
            dk_entry_t *dk_entries = malloc(num_dirty * sizeof(dk_entry_t));
            for (uint32_t d = 0; d < num_dirty; d++) {
                dk_entries[d].key = dirty_keys + d * 32;
                dk_entries[d].val = dirty_val_buf + dirty_val_offsets[d];
                dk_entries[d].vlen = dirty_vlens[d];
            }
            // Sort dirty entries by key
            for (uint32_t i = 1; i < num_dirty; i++) {
                dk_entry_t tmp = dk_entries[i];
                uint32_t j = i;
                while (j > 0 && memcmp(dk_entries[j-1].key, tmp.key, 32) > 0) {
                    dk_entries[j] = dk_entries[j-1];
                    j--;
                }
                dk_entries[j] = tmp;
            }
            const uint8_t **dk_ptrs = malloc(num_dirty * sizeof(uint8_t *));
            const uint8_t **dv_ptrs = malloc(num_dirty * sizeof(uint8_t *));
            size_t *sorted_dirty_vlens = malloc(num_dirty * sizeof(size_t));
            for (uint32_t d = 0; d < num_dirty; d++) {
                dk_ptrs[d] = dk_entries[d].key;
                dv_ptrs[d] = dk_entries[d].val;
                sorted_dirty_vlens[d] = dk_entries[d].vlen;
            }
            free(dk_entries);

            // Step 4: ih_update
            hash_t update_root = ih_update(ih, dk_ptrs, dv_ptrs,
                                           sorted_dirty_vlens, num_dirty, &cursor);

            print_hash("expected", &expected_after);
            print_hash("got     ", &update_root);

            // Step 5: Also verify ih_build on merged gives same result
            ih_state_t *ih2 = ih_create();
            uint16_t *merged_vlens16 = malloc(merged_count * sizeof(uint16_t));
            for (size_t i = 0; i < merged_count; i++)
                merged_vlens16[i] = (uint16_t)cursor_vlens[i];

            hash_t rebuild_root = ih_build(ih2, cursor_keys, cursor_vals,
                                           merged_vlens16, merged_count);

            ASSERT(hash_equal(&update_root, &expected_after));
            ASSERT(hash_equal(&rebuild_root, &expected_after));

            // Cleanup
            free(merged_vlens16);
            free(dk_ptrs);
            free(dv_ptrs);
            free(sorted_dirty_vlens);
            free(cursor_keys);
            free(cursor_vals);
            free(cursor_vlens);
            free(merged);
            free(init_key_ptrs);
            free(init_val_ptrs);
            free(init_vlens);
            free(dirty_keys);
            free(dirty_val_buf);
            free(dirty_val_offsets);
            free(dirty_vlens);
            ih_destroy(ih);
            ih_destroy(ih2);
            free_kv_set(&initial);
            update_pass++;
            printf("    PASS\n\n");
        }
    }

    fclose(f);

    printf("=== CROSS-VALIDATION COMPLETE ===\n");
    printf("  Build scenarios:  %d passed\n", build_pass);
    printf("  Update scenarios: %d passed\n", update_pass);
    printf("  Total assertions: %d\n", assertions);
    return 0;
}
