#include "mpt.h"
#include "hash.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <inttypes.h>
#include <assert.h>
#include <unistd.h>

/**
 * Cross-validation test: compare mpt_root() against Python's HexaryTrie
 * (reference Ethereum MPT implementation).
 *
 * Reads test vectors from mpt_vectors.bin generated by gen_mpt_vectors.py.
 * Scenario types: 0=build, 1=update, 2=multiblock.
 */

#define MPT_PATH "/tmp/test_mpt_cross_val.dat"

static int assertions = 0;
#define ASSERT(cond) do { \
    assertions++; \
    if (!(cond)) { \
        fprintf(stderr, "FAIL: %s:%d: %s\n", __FILE__, __LINE__, #cond); \
        abort(); \
    } \
} while(0)

static void print_hash(const char *label, const hash_t *h) {
    printf("    %s: ", label);
    for (int i = 0; i < 32; i++) printf("%02x", h->bytes[i]);
    printf("\n");
}

// ============================================================================
// Binary file reader helpers
// ============================================================================

static uint32_t read_u32(FILE *f) {
    uint8_t buf[4];
    ASSERT(fread(buf, 1, 4, f) == 4);
    return buf[0] | (buf[1] << 8) | (buf[2] << 16) | (buf[3] << 24);
}

static uint16_t read_u16(FILE *f) {
    uint8_t buf[2];
    ASSERT(fread(buf, 1, 2, f) == 2);
    return buf[0] | (buf[1] << 8);
}

static uint8_t read_u8(FILE *f) {
    uint8_t b;
    ASSERT(fread(&b, 1, 1, f) == 1);
    return b;
}

static void read_hash(FILE *f, hash_t *h) {
    ASSERT(fread(h->bytes, 1, 32, f) == 32);
}

typedef struct {
    uint8_t *keys;       // count * 32 bytes
    uint8_t *values;     // concatenated values
    size_t *val_offsets;
    size_t *val_lens;
    size_t count;
} kv_set_t;

static kv_set_t read_kv_set(FILE *f) {
    kv_set_t kv = {0};
    kv.count = read_u32(f);

    if (kv.count == 0) return kv;

    kv.keys = malloc(kv.count * 32);
    kv.val_offsets = malloc(kv.count * sizeof(size_t));
    kv.val_lens = malloc(kv.count * sizeof(size_t));

    // First pass: measure total value bytes
    size_t total_val = 0;
    long keys_start = ftell(f);
    for (size_t i = 0; i < kv.count; i++) {
        fseek(f, 32, SEEK_CUR);
        uint16_t vlen = read_u16(f);
        total_val += vlen;
        fseek(f, vlen, SEEK_CUR);
    }
    kv.values = malloc(total_val > 0 ? total_val : 1);

    // Second pass: read data
    fseek(f, keys_start, SEEK_SET);
    size_t voff = 0;
    for (size_t i = 0; i < kv.count; i++) {
        ASSERT(fread(kv.keys + i * 32, 1, 32, f) == 32);
        uint16_t vlen = read_u16(f);
        kv.val_lens[i] = vlen;
        kv.val_offsets[i] = voff;
        if (vlen > 0)
            ASSERT(fread(kv.values + voff, 1, vlen, f) == vlen);
        voff += vlen;
    }
    return kv;
}

static void free_kv_set(kv_set_t *kv) {
    free(kv->keys);
    free(kv->values);
    free(kv->val_offsets);
    free(kv->val_lens);
    memset(kv, 0, sizeof(*kv));
}

// ============================================================================
// Dirty set reader
// ============================================================================

typedef struct {
    uint8_t *keys;
    uint8_t *val_buf;
    size_t *val_offsets;
    size_t *vlens;
    uint32_t count;
} dirty_set_t;

static dirty_set_t read_dirty_set(FILE *f) {
    dirty_set_t ds = {0};
    ds.count = read_u32(f);
    if (ds.count == 0) return ds;

    ds.keys = malloc(ds.count * 32);
    ds.val_offsets = malloc(ds.count * sizeof(size_t));
    ds.vlens = malloc(ds.count * sizeof(size_t));

    // First pass: measure total value bytes
    size_t total = 0;
    long start = ftell(f);
    for (uint32_t d = 0; d < ds.count; d++) {
        fseek(f, 32, SEEK_CUR);
        uint16_t vlen = read_u16(f);
        total += vlen;
        fseek(f, vlen, SEEK_CUR);
    }
    ds.val_buf = malloc(total > 0 ? total : 1);

    // Second pass: read
    fseek(f, start, SEEK_SET);
    size_t off = 0;
    for (uint32_t d = 0; d < ds.count; d++) {
        ASSERT(fread(ds.keys + d * 32, 1, 32, f) == 32);
        uint16_t vlen = read_u16(f);
        ds.vlens[d] = vlen;
        ds.val_offsets[d] = off;
        if (vlen > 0)
            ASSERT(fread(ds.val_buf + off, 1, vlen, f) == vlen);
        off += vlen;
    }
    return ds;
}

static void free_dirty_set(dirty_set_t *ds) {
    free(ds->keys);
    free(ds->val_buf);
    free(ds->val_offsets);
    free(ds->vlens);
    memset(ds, 0, sizeof(*ds));
}

// ============================================================================
// MPT helpers
// ============================================================================

/* Insert all entries from a kv_set into the mpt */
static void mpt_put_kv_set(mpt_t *m, const kv_set_t *kv) {
    for (size_t i = 0; i < kv->count; i++) {
        bool ok = mpt_put(m, kv->keys + i * 32,
                          kv->values + kv->val_offsets[i],
                          (uint8_t)kv->val_lens[i]);
        ASSERT(ok);
    }
}

/* Apply dirty set: put (vlen > 0) or delete (vlen == 0) */
static void mpt_apply_dirty(mpt_t *m, const dirty_set_t *ds) {
    for (uint32_t d = 0; d < ds->count; d++) {
        const uint8_t *dk = ds->keys + d * 32;
        if (ds->vlens[d] > 0) {
            bool ok = mpt_put(m, dk,
                              ds->val_buf + ds->val_offsets[d],
                              (uint8_t)ds->vlens[d]);
            ASSERT(ok);
        } else {
            mpt_delete(m, dk);
        }
    }
}

// ============================================================================
// Main
// ============================================================================

int main(void) {
    printf("=== MPT Cross-Validation (Python HexaryTrie reference) ===\n\n");

    FILE *f = fopen("database/tests/mpt_vectors.bin", "rb");
    if (!f)
        f = fopen("../database/tests/mpt_vectors.bin", "rb");
    if (!f) {
        fprintf(stderr, "ERROR: mpt_vectors.bin not found.\n"
                "Run: ./venv/bin/python3 database/tests/gen_mpt_vectors.py\n");
        return 1;
    }

    uint32_t num_scenarios = read_u32(f);
    printf("Loaded %u scenarios from mpt_vectors.bin\n\n", num_scenarios);

    int build_pass = 0, update_pass = 0, multiblock_pass = 0;

    for (uint32_t s = 0; s < num_scenarios; s++) {
        uint8_t stype = read_u8(f);

        if (stype == 0) {
            // ---- Build scenario ----
            kv_set_t kv = read_kv_set(f);
            hash_t expected;
            read_hash(f, &expected);

            printf("Scenario %u [BUILD]: %zu keys\n", s + 1, kv.count);

            unlink(MPT_PATH);
            mpt_t *m = mpt_create(MPT_PATH);
            ASSERT(m != NULL);

            mpt_put_kv_set(m, &kv);
            hash_t root = mpt_root(m);

            print_hash("expected", &expected);
            print_hash("got     ", &root);
            ASSERT(hash_equal(&root, &expected));

            mpt_close(m);
            unlink(MPT_PATH);
            free_kv_set(&kv);
            build_pass++;
            printf("    PASS\n\n");

        } else if (stype == 1) {
            // ---- Update scenario (single dirty block) ----
            kv_set_t initial = read_kv_set(f);
            hash_t initial_root;
            read_hash(f, &initial_root);

            dirty_set_t ds = read_dirty_set(f);
            hash_t expected_after;
            read_hash(f, &expected_after);

            printf("Scenario %u [UPDATE]: %zu initial + %u dirty\n",
                   s + 1, initial.count, ds.count);

            unlink(MPT_PATH);
            mpt_t *m = mpt_create(MPT_PATH);
            ASSERT(m != NULL);

            // Insert initial keys and verify initial root
            mpt_put_kv_set(m, &initial);
            hash_t built_root = mpt_root(m);
            ASSERT(hash_equal(&built_root, &initial_root));

            // Apply dirty ops and verify updated root
            mpt_apply_dirty(m, &ds);
            hash_t update_root = mpt_root(m);

            print_hash("expected", &expected_after);
            print_hash("got     ", &update_root);
            ASSERT(hash_equal(&update_root, &expected_after));

            mpt_close(m);
            unlink(MPT_PATH);
            free_dirty_set(&ds);
            free_kv_set(&initial);
            update_pass++;
            printf("    PASS\n\n");

        } else if (stype == 2) {
            // ---- Multi-block scenario ----
            kv_set_t initial = read_kv_set(f);
            hash_t initial_root;
            read_hash(f, &initial_root);

            uint32_t num_blocks = read_u32(f);

            printf("Scenario %u [MULTIBLOCK]: %zu initial, %u blocks\n",
                   s + 1, initial.count, num_blocks);

            unlink(MPT_PATH);
            mpt_t *m = mpt_create(MPT_PATH);
            ASSERT(m != NULL);

            // Build initial state
            mpt_put_kv_set(m, &initial);
            hash_t built_root = mpt_root(m);
            ASSERT(hash_equal(&built_root, &initial_root));

            for (uint32_t blk = 0; blk < num_blocks; blk++) {
                dirty_set_t ds = read_dirty_set(f);
                hash_t expected;
                read_hash(f, &expected);

                mpt_apply_dirty(m, &ds);
                hash_t root = mpt_root(m);

                printf("  block %u/%u: %u dirty, %" PRIu64 " total keys\n",
                       blk + 1, num_blocks, ds.count, mpt_size(m));

                print_hash("expected", &expected);
                print_hash("got     ", &root);
                ASSERT(hash_equal(&root, &expected));

                free_dirty_set(&ds);
            }

            mpt_close(m);
            unlink(MPT_PATH);
            free_kv_set(&initial);
            multiblock_pass++;
            printf("    PASS\n\n");

        } else {
            fprintf(stderr, "ERROR: unknown scenario type %u\n", stype);
            return 1;
        }
    }

    fclose(f);

    printf("=== CROSS-VALIDATION COMPLETE ===\n");
    printf("  Build scenarios:      %d passed\n", build_pass);
    printf("  Update scenarios:     %d passed\n", update_pass);
    printf("  Multi-block scenarios: %d passed\n", multiblock_pass);
    printf("  Total assertions:     %d\n", assertions);
    return 0;
}
